import { CaretLeftIcon } from '@phosphor-icons/react/CaretLeft';
import { CaretRightIcon } from '@phosphor-icons/react/CaretRight';

export interface PlanningFilters { machineId: string; order: string; collection: string; erp: string }
interface Props { weekStart: string; timezone: string; filters: PlanningFilters; machines: Array<{ id: number; name: string }>; refreshedAt?: Date; onWeekChange: (delta: number) => void; onCurrentWeek: () => void; onFiltersChange: (filters: PlanningFilters) => void; onCreate: () => void; onImport: () => void; canPlan: boolean; canImport: boolean; loading?: boolean }

export function ProductionWeekToolbar({ weekStart, timezone, filters, machines, refreshedAt, onWeekChange, onCurrentWeek, onFiltersChange, onCreate, onImport, canPlan, canImport, loading }: Props) {
  const date = new Date(`${weekStart}T12:00:00Z`);
  const label = Number.isNaN(date.getTime()) ? weekStart : new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' }).format(date);
  return <section className="planning-toolbar" aria-label="Commandes du planning"><div className="planning-week-nav"><button className="button-secondary" type="button" aria-label="Semaine précédente" onClick={() => onWeekChange(-1)}><CaretLeftIcon size={18} aria-hidden="true" /></button><div><strong>Semaine du {label}</strong><span>Fuseau du site : {timezone}</span></div><button className="button-secondary" type="button" aria-label="Semaine suivante" onClick={() => onWeekChange(1)}><CaretRightIcon size={18} aria-hidden="true" /></button><button className="button-ghost" type="button" onClick={onCurrentWeek}>Cette semaine</button></div><div className="planning-actions"><span className="planning-refreshed" role="status">{loading ? 'Actualisation…' : refreshedAt ? `Actualisé à ${refreshedAt.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}` : 'Pas encore actualisé'}</span><button className="button-secondary" type="button" onClick={onImport} disabled={!canImport}>Importer l’ERP</button><button className="button-primary" type="button" onClick={onCreate} disabled={!canPlan}>Planifier un OF</button></div><div className="planning-filters"><label>Presse<select value={filters.machineId} onChange={event => onFiltersChange({ ...filters, machineId: event.target.value })}><option value="">Toutes les presses</option>{machines.map(machine => <option key={machine.id} value={machine.id}>{machine.name}</option>)}</select></label><label>OF<input value={filters.order} onChange={event => onFiltersChange({ ...filters, order: event.target.value })} placeholder="Rechercher un OF" /></label><label>Collecte<select value={filters.collection} onChange={event => onFiltersChange({ ...filters, collection: event.target.value })}><option value="">Tous les états</option><option value="no_cycle">Aucun cycle</option><option value="receiving">Réception active</option><option value="interrupted">Interrompue</option><option value="partial">Partielle</option></select></label><label>ERP<select value={filters.erp} onChange={event => onFiltersChange({ ...filters, erp: event.target.value })}><option value="">Tous les états</option><option value="pending">En attente</option><option value="matched">Rapproché</option><option value="incomplete">Incomplet</option><option value="conflict">Conflit</option></select></label></div></section>;
}
