import { useQuery } from '@tanstack/react-query';
import { useApi } from '../App';
import { EmptyPanel, formatDate, MetricCard, SectionTitle, StatePanel } from '../components/Ui';

export function ImportsPage() {
  const api = useApi();
  const query = useQuery({ queryKey: ['imports'], queryFn: api.getImports });
  const imports = query.data ?? [];
  const completed = imports.filter((item) => item.status === 'completed').length;
  const rejected = imports.reduce((total, item) => total + (item.rowCountRejected ?? 0), 0);
  return <section className="page page-wide"><div className="page-intro"><div><p className="eyebrow">TRAÇABILITÉ DES DONNÉES</p><h2>Historique des imports</h2><p className="muted">Les passeports d’import rendent chaque ligne source rejouable et expliquent les éventuels rejets.</p></div><button className="button-primary" type="button" onClick={() => query.refetch()} disabled={query.isFetching}>{query.isFetching ? 'Actualisation…' : 'Actualiser'}</button></div>{query.isPending && <StatePanel tone="loading" title="Chargement des passeports" text="Le journal d’import est en cours de récupération." />}{query.isError && <StatePanel tone="error" title="Journal indisponible" text={query.error instanceof Error ? query.error.message : 'Impossible de lire les imports.'} action="Réessayer" onAction={() => query.refetch()} />}{!query.isPending && !query.isError && imports.length === 0 && <EmptyPanel title="Aucun import enregistré" text="Le worker d’ingestion publiera ici le premier passeport traité." />}{!query.isPending && !query.isError && imports.length > 0 && <><div className="metric-grid metric-grid-three"><MetricCard label="Fichiers suivis" value={imports.length} detail="passeports" /><MetricCard label="Terminés" value={completed} detail="prêts à requêter" tone="good" /><MetricCard label="Lignes rejetées" value={rejected} detail="sur le périmètre chargé" tone={rejected ? 'warning' : 'good'} /></div><section className="surface-card import-table-card"><SectionTitle eyebrow="PASSEPORTS" title="Fichiers traités" /><div className="incident-table-wrap"><table className="incident-table import-table"><caption className="visually-hidden">Journal des imports</caption><thead><tr><th scope="col">Fichier</th><th scope="col">Parser</th><th scope="col">Statut</th><th scope="col">Lignes</th><th scope="col">Importé le</th></tr></thead><tbody>{imports.map((item) => <tr key={item.id}><td><strong>{item.fileName ?? item.id}</strong><small>{item.id.slice(0, 12)}</small></td><td>{item.parserType ?? '—'}</td><td><span className={`status-label status-label-${item.status}`}>{item.status === 'completed' ? 'Terminé' : item.status === 'failed' ? 'En erreur' : 'En attente'}</span>{item.errorLog && <small className="helper-error">{item.errorLog}</small>}</td><td><span className="number-cell">{item.rowCountAccepted ?? 0}</span><small>/ {item.rowCountTotal ?? '—'} acceptées</small></td><td>{formatDate(item.importedAt)}</td></tr>)}</tbody></table></div></section></>}</section>;
}
