import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FormEvent, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useApi } from '../App';
import { EmptyPanel, formatDate, formatNumber, formatPercent, incidentSeverityLabel, MetricCard, SectionTitle, StatePanel } from '../components/Ui';
import type { Evidence, Hypothesis } from '../lib/api';

function evidenceValue(evidence: Evidence, field: string): number | undefined {
  const value = evidence.observation[field];
  return typeof value === 'number' ? value : undefined;
}

function EvidenceRow({ evidence }: { evidence: Evidence }) {
  const observation = evidenceValue(evidence, 'value');
  const baseline = evidence.baseline && typeof evidence.baseline.value === 'number' ? evidence.baseline.value : undefined;
  const unit = typeof evidence.observation.unit === 'string' ? evidence.observation.unit : '';
  return <article className={`evidence-row ${evidence.supports ? 'supports' : 'contradicts'}`}><div className="evidence-mark" aria-hidden="true">{evidence.supports ? '✓' : '×'}</div><div className="evidence-main"><div className="evidence-heading"><strong>{evidence.metric.split('_').join(' ')}</strong><span>{evidence.source_kind.split('_').join(' ')}</span></div><p>{observation !== undefined ? `${formatNumber(observation, 2)} ${unit}` : evidence.excerpt ?? 'Observation structurée'}</p>{baseline !== undefined && <small>Baseline : {formatNumber(baseline, 2)} {typeof evidence.baseline?.unit === 'string' ? evidence.baseline.unit : unit} · Δ {evidence.delta !== null && evidence.delta !== undefined ? formatNumber(evidence.delta, 2) : '—'}</small>}{evidence.excerpt && observation !== undefined && <small className="evidence-excerpt">“{evidence.excerpt}”</small>}</div><div className="evidence-window">{formatDate(evidence.window.start, false)}<br /><span>→ {formatDate(evidence.window.end, false)}</span></div></article>;
}

export function IncidentDetailPage() {
  const { incidentId = '' } = useParams();
  const api = useApi();
  const queryClient = useQueryClient();
  const [feedbackVerdict, setFeedbackVerdict] = useState('confirmed');
  const [feedbackComment, setFeedbackComment] = useState('');
  const [feedbackSent, setFeedbackSent] = useState(false);
  const incidentQuery = useQuery({ queryKey: ['incident', incidentId], queryFn: () => api.getIncident(incidentId), enabled: Boolean(incidentId) });
  const evidenceQuery = useQuery({ queryKey: ['incident-evidence', incidentId], queryFn: () => api.getEvidence(incidentId), enabled: Boolean(incidentId) });
  const investigationMutation = useMutation({ mutationFn: () => api.runInvestigation(incidentId, incidentQuery.data?.data_cutoff), onSuccess: (result) => { queryClient.setQueryData(['incident-evidence', incidentId], result.evidence); queryClient.setQueryData(['incident-investigation', incidentId], result); } });
  const feedbackMutation = useMutation({ mutationFn: () => api.submitFeedback(incidentId, feedbackVerdict, feedbackComment || undefined), onSuccess: () => { setFeedbackSent(true); setFeedbackComment(''); } });
  const investigationQuery = useQuery({ queryKey: ['incident-investigation', incidentId], queryFn: () => api.runInvestigation(incidentId, incidentQuery.data?.data_cutoff), enabled: false });
  const evidence = evidenceQuery.data ?? investigationQuery.data?.evidence ?? [];
  const hypothesis: Hypothesis | undefined = investigationQuery.data?.hypotheses?.[0];
  const scrapEvidence = evidence.find((item) => item.metric === 'scrap_rate');
  const temperatureEvidence = evidence.find((item) => item.metric === 'barrel_temp_zone2_c');
  const timeline = useMemo(() => incidentQuery.data ? [{ label: 'Avant', date: new Date(new Date(incidentQuery.data.started_at).getTime() - 60 * 60 * 1000).toISOString(), tone: 'before' }, { label: 'Pendant', date: incidentQuery.data.started_at, tone: 'during' }, { label: 'Fin du signal', date: incidentQuery.data.ended_at ?? incidentQuery.data.data_cutoff, tone: 'during' }, { label: 'Après / cutoff', date: incidentQuery.data.data_cutoff, tone: 'after' }] : [], [incidentQuery.data]);

  function submitFeedback(event: FormEvent) { event.preventDefault(); feedbackMutation.mutate(); }
  if (incidentQuery.isPending) return <section className="page"><StatePanel tone="loading" title="Chargement de l’incident" text="Le contexte et les preuves sont en cours de récupération." /></section>;
  if (incidentQuery.isError || !incidentQuery.data) return <section className="page"><StatePanel tone="error" title="Incident introuvable" text={incidentQuery.error instanceof Error ? incidentQuery.error.message : 'Ce signal n’existe pas ou n’est plus accessible.'} action="Retour aux incidents" onAction={() => window.history.back()} /></section>;
  const incident = incidentQuery.data;
  return <section className="page page-wide incident-detail-page">
    <div className="page-intro"><div><Link className="back-link" to="/incidents">← Tous les incidents</Link><p className="eyebrow">INCIDENT · {incident.id.slice(0, 8)}</p><h2>{incident.symptom.split('_').join(' ')}</h2><p className="muted">Presse {incident.machine_erp_ref ?? incident.machine_id} · OF {incident.production_order_id ?? 'non renseigné'} · créé le {formatDate(incident.created_at)}</p></div><div className="detail-actions"><span className={`severity severity-${incident.severity}`}>{incidentSeverityLabel(incident.severity)}</span><button type="button" className="button-primary" onClick={() => investigationMutation.mutate()} disabled={investigationMutation.isPending}>{investigationMutation.isPending ? 'Investigation…' : 'Lancer l’investigation'}</button></div></div>
    {investigationMutation.isError && <StatePanel tone="error" title="Investigation impossible" text={investigationMutation.error instanceof Error ? investigationMutation.error.message : 'Le moteur déterministe n’a pas pu produire de résultat.'} action="Réessayer" onAction={() => investigationMutation.mutate()} />}
    {investigationMutation.isSuccess && <StatePanel tone="success" title="Investigation terminée" text="Les chiffres affichés ci-dessous proviennent du run déterministe persisté." />}
    <div className="detail-summary"><MetricCard label="Fenêtre du signal" value={formatDate(incident.started_at, false)} detail={`jusqu’au ${formatDate(incident.ended_at ?? incident.data_cutoff, false)}`} /><MetricCard label="Rebut observé" value={scrapEvidence ? formatPercent(evidenceValue(scrapEvidence, 'value')) : '—'} detail={scrapEvidence?.baseline ? `baseline ${formatPercent(typeof scrapEvidence.baseline.value === 'number' ? scrapEvidence.baseline.value : undefined)}` : 'preuve à calculer'} tone={scrapEvidence?.supports ? 'danger' : 'neutral'} /><MetricCard label="Zone 2" value={temperatureEvidence ? `${formatNumber(evidenceValue(temperatureEvidence, 'value'), 1)} °C` : '—'} detail={temperatureEvidence?.baseline ? `baseline ${formatNumber(typeof temperatureEvidence.baseline.value === 'number' ? temperatureEvidence.baseline.value : undefined, 1)} °C` : 'preuve à calculer'} tone={temperatureEvidence?.supports ? 'warning' : 'neutral'} /><MetricCard label="Confiance" value={incident.confidence ?? '—'} detail="classification serveur" tone={incident.confidence === 'high' ? 'good' : 'warning'} /></div>
    <section className="surface-card timeline-card"><SectionTitle eyebrow="RECONSTITUTION TEMPORELLE" title="Avant · pendant · après" /><div className="investigation-timeline">{timeline.map((item) => <div key={item.label} className={`timeline-step ${item.tone}`}><span className="timeline-dot" aria-hidden="true" /><strong>{item.label}</strong><time dateTime={item.date}>{formatDate(item.date)}</time></div>)}</div><p className="timeline-cutoff">Cutoff de données : <strong>{formatDate(incident.data_cutoff)}</strong>. L’heure courante n’est jamais utilisée pour ce replay.</p></section>
    <div className="investigation-grid"><section className="surface-card hypotheses-card"><SectionTitle eyebrow="RAISONNEMENT STRUCTURÉ" title="Hypothèses"><p className="muted small">{hypothesis ? 'La première cause est classée par le moteur local.' : 'Lancez une investigation pour produire des hypothèses et leurs liens de preuve.'}</p></SectionTitle>{hypothesis ? <article className="hypothesis-card"><div className="hypothesis-confidence"><strong>{Math.round(hypothesis.confidence * 100)}%</strong><span>confiance</span></div><div><h3>{hypothesis.label}</h3><p>{hypothesis.cause_code}</p>{hypothesis.next_check && <div className="next-check"><strong>Prochaine vérification</strong><span>{hypothesis.next_check.split('_').join(' ')}</span></div>}</div></article> : <EmptyPanel title="Aucun run disponible" text="Le moteur local attend une action humaine pour démarrer l’analyse." />}</section><section className="surface-card evidence-card"><SectionTitle eyebrow="EVIDENCE VAULT" title="Preuves citées"><span className="evidence-count">{evidence.length} preuve{evidence.length > 1 ? 's' : ''}</span></SectionTitle>{evidence.length === 0 ? <EmptyPanel title="Preuves non calculées" text="Aucune valeur n’est inventée : lancez l’investigation pour recalculer la fenêtre." /> : <div className="evidence-list">{evidence.map((item) => <EvidenceRow key={item.id} evidence={item} />)}</div>}</section></div>
    <section className="surface-card feedback-card"><SectionTitle eyebrow="VALIDATION HUMAINE" title="Votre retour"><p className="muted small">Ce retour est enregistré avec l’incident pour améliorer la recette.</p></SectionTitle>{feedbackSent ? <StatePanel tone="success" title="Retour enregistré" text="Merci. Votre verdict est associé à cet incident." action="Modifier le retour" onAction={() => setFeedbackSent(false)} /> : <form className="feedback-form" onSubmit={submitFeedback}><label htmlFor="feedback-verdict">Verdict</label><select id="feedback-verdict" value={feedbackVerdict} onChange={(event) => setFeedbackVerdict(event.target.value)}><option value="confirmed">Cause confirmée</option><option value="rejected">Cause rejetée</option><option value="uncertain">À confirmer</option></select><label htmlFor="feedback-comment">Commentaire <span>(facultatif)</span></label><textarea id="feedback-comment" value={feedbackComment} onChange={(event) => setFeedbackComment(event.target.value)} maxLength={4000} rows={3} placeholder="Ajoutez un constat terrain…" /><div className="feedback-submit"><span className="muted">Le commentaire reste rattaché à l’incident.</span><button className="button-primary" type="submit" disabled={feedbackMutation.isPending}>{feedbackMutation.isPending ? 'Enregistrement…' : 'Enregistrer le retour'}</button></div>{feedbackMutation.isError && <p className="helper-error">Impossible d’enregistrer le retour. Réessayez.</p>}</form>}</section>
  </section>;
}
